#!/usr/bin/env node
// Sync content/schemas/galaxy-tool-discovery.schema.json into this package's src/.
// Source of truth lives in the Foundry's content/ tree (mold/schema/cast loop edits it);
// the package mirrors it under src/ and regenerates the typed const.

import { copyFileSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const PKG_ROOT = resolve(__dirname, "..");
const FOUNDRY_ROOT = resolve(PKG_ROOT, "..", "..");

const SRC_JSON = resolve(FOUNDRY_ROOT, "content/schemas/galaxy-tool-discovery.schema.json");
const DST_JSON = resolve(PKG_ROOT, "src/galaxy-tool-discovery.schema.json");
const DST_TS = resolve(PKG_ROOT, "src/galaxy-tool-discovery.schema.generated.ts");

copyFileSync(SRC_JSON, DST_JSON);

const schema = JSON.parse(readFileSync(SRC_JSON, "utf8"));
const banner =
  "// Generated by scripts/sync-schema.mjs. Do not edit.\n" +
  "// Source of truth: content/schemas/galaxy-tool-discovery.schema.json in the Foundry repo.\n";
const body = `export const galaxyToolDiscoverySchema = ${JSON.stringify(schema, null, 2)} as const;\n`;
writeFileSync(DST_TS, banner + body);

console.log(`synced ${SRC_JSON} -> ${DST_JSON}`);
console.log(`generated ${DST_TS}`);
