#!/usr/bin/env node
// Sync @galaxy-tool-util/schema's testsSchema into Foundry artifacts.

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { testsSchema } from "@galaxy-tool-util/schema";

const __dirname = dirname(fileURLToPath(import.meta.url));
const PKG_ROOT = resolve(__dirname, "..");
const FOUNDRY_ROOT = resolve(PKG_ROOT, "..", "..");

const CONTENT_JSON = resolve(FOUNDRY_ROOT, "content/schemas/tests.schema.json");
const DST_JSON = resolve(PKG_ROOT, "src/tests.schema.json");
const DST_TS = resolve(PKG_ROOT, "src/tests.schema.generated.ts");

const json = JSON.stringify(testsSchema, null, 2) + "\n";
mkdirSync(dirname(CONTENT_JSON), { recursive: true });
mkdirSync(dirname(DST_JSON), { recursive: true });
writeFileSync(CONTENT_JSON, json);
writeFileSync(DST_JSON, json);

const banner =
  "// Generated by scripts/sync-schema.mjs. Do not edit.\n" +
  "// Source of truth: @galaxy-tool-util/schema testsSchema.\n";
writeFileSync(DST_TS, `${banner}export const testsFormatSchema = ${json.trim()} as const;\n`);

console.log(`synced ${CONTENT_JSON}`);
console.log(`synced ${DST_JSON}`);
console.log(`generated ${DST_TS}`);
