#!/usr/bin/env node
// Sync @galaxy-tool-util/schema's testsSchema into this package's src/.
// Upstream is the source of truth; the Foundry's content/schemas/ no longer
// holds a JSON copy — cast and Astro resolve schema refs back to this
// package at build time.

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { testsSchema } from "@galaxy-tool-util/schema";

const __dirname = dirname(fileURLToPath(import.meta.url));
const PKG_ROOT = resolve(__dirname, "..");

const DST_JSON = resolve(PKG_ROOT, "src/tests.schema.json");
const DST_TS = resolve(PKG_ROOT, "src/tests.schema.generated.ts");

const json = JSON.stringify(testsSchema, null, 2) + "\n";
mkdirSync(dirname(DST_JSON), { recursive: true });
writeFileSync(DST_JSON, json);

const banner =
  "// Generated by scripts/sync-schema.mjs. Do not edit.\n" +
  "// Source of truth: @galaxy-tool-util/schema testsSchema.\n";
writeFileSync(DST_TS, `${banner}export const testsFormatSchema = ${json.trim()} as const;\n`);

console.log(`synced ${DST_JSON}`);
console.log(`generated ${DST_TS}`);
